Repository 2501-ai/cli, pull requests merged in 2025-06, with the labels that each got.

#152 making the CLI output crop strategy more strict to avoid hallucinatio…
  package-lock.json
  package.json
  src/managers/agentManager.ts
Labels: Review effort 2/5

#150 fix(errorHandler): send error to engine
  .vscode/launch.json
  package-lock.json
  package.json
  src/commands/agents.ts
  src/commands/config.ts
  src/commands/init.ts
  src/commands/query.ts
  src/commands/set.ts
  src/index.ts
  src/managers/configManager.ts
  src/managers/telemetryManager.ts
  src/middleware/auth.ts
  src/middleware/errorHandler.ts
  src/telemetry/errorTracker.ts
  src/telemetry/index.ts
  src/telemetry/types.ts
  src/utils/logger.ts
  src/utils/types.ts
  yarn.lock
Labels: Review effort 3/5

#157 hotfix/final response debug
  package-lock.json
  package.json
  src/commands/query.ts
  src/telemetry/errorTracker.ts
  src/utils/logger.ts
Labels: Review effort 2/5

#159 fix: removed duplicate call to write file that could cause issues to sudo update file
  package-lock.json
  package.json
  src/helpers/actions.ts
Labels: Review effort 2/5

#161 feat: add public_ip
  package.json
  src/helpers/api.ts
  src/utils/systemInfo.ts
  src/utils/types.ts
Labels: Review effort 3/5, Possible security concern

#154 hotfix/windows installer
  installers/README.md
  installers/linux-installer.sh
  installers/macOS-installer.sh
  installers/windows-installer.bat
  installers/windows-installer.ps1
  package-lock.json
  package.json
  src/commands/init.ts
  src/commands/tasks.ts
  src/constants.ts
  src/helpers/actions.ts
  src/helpers/security.ts
  src/helpers/workspace.ts
  src/index.ts
  src/utils/platform.ts
  src/utils/systemInfo.ts
Labels: Review effort 2/5
